# Controller manager configuration
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_true: true

    ### Controllers available
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    LAposition_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    RAposition_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    RFposition_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    LFposition_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    LRposition_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    RRposition_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


### Properties of the controllers that we will use and definition of joints to use ###
forward_position_controller:
  ros__parameters:
    joints:
      - left_arm_joint1
      - left_arm_joint2
      - left_arm_joint3
      - left_arm_joint4
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - f_left_leg_joint1
      - f_right_leg_joint1
      - b_left_leg_joint1
      - b_right_leg_joint1
      - f_left_leg_joint2
      - f_right_leg_joint2
      - b_left_leg_joint2
      - b_right_leg_joint2
      - f_left_leg_joint3
      - f_right_leg_joint3
      - b_left_leg_joint3
      - b_right_leg_joint3

    interface_name: position


LAposition_trajectory_controller:
  ros__parameters:
    joints:
      - left_arm_joint1
      - left_arm_joint2
      - left_arm_joint3
      - left_arm_joint4
      - left_arm_joint5
      - left_arm_joint6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Hz, Defaults to 50
    action_monitor_rate: 20.0 # Hz, Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

    gains:
      left_arm_joint1:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      left_arm_joint2:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      left_arm_joint3:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0

RAposition_trajectory_controller:
  ros__parameters:
    joints:
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Hz, Defaults to 50
    action_monitor_rate: 20.0 # Hz, Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

    gains:
      right_arm_joint1:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      right_arm_joint2:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      right_arm_joint3:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0



RFposition_trajectory_controller:
  ros__parameters:
    joints:
      - f_right_leg_joint1
      - f_right_leg_joint2
      - f_right_leg_joint3

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Hz, Defaults to 50
    action_monitor_rate: 20.0 # Hz, Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

    gains:
      f_right_leg_joint1:
          p: 1500.0
          i: 5.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      f_right_leg_joint2:
          p: 2000.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      f_right_leg_joint3:
          p: 2000.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0

LFposition_trajectory_controller:
  ros__parameters:
    joints:
      - f_left_leg_joint1
      - f_left_leg_joint2
      - f_left_leg_joint3

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Hz, Defaults to 50
    action_monitor_rate: 20.0 # Hz, Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

    gains:
      f_left_leg_joint1:
          p: 1500.0
          i: 5.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      f_left_leg_joint2:
          p: 2000.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      f_left_leg_joint3:
          p: 2000.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0

LRposition_trajectory_controller:
  ros__parameters:
    joints:
      - b_left_leg_joint1
      - b_left_leg_joint2
      - b_left_leg_joint3

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Hz, Defaults to 50
    action_monitor_rate: 20.0 # Hz, Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

    gains:
      b_left_leg_joint1:
          p: 1500.0
          i: 5.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      b_left_leg_joint2:
          p: 2000.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      b_left_leg_joint3:
          p: 2000.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0

RRposition_trajectory_controller:
  ros__parameters:
    joints:
      - b_right_leg_joint1
      - b_right_leg_joint2
      - b_right_leg_joint3

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Hz, Defaults to 50
    action_monitor_rate: 20.0 # Hz, Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

    gains:
      b_right_leg_joint1:
          p: 1500.0
          i: 5.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      b_right_leg_joint2:
          p: 2000.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      b_right_leg_joint3:
          p: 2000.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0


position_trajectory_controller:
  ros__parameters:
    joints:
      - left_arm_joint1
      - left_arm_joint2
      - left_arm_joint3
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - f_left_leg_joint1
      - f_right_leg_joint1
      - b_left_leg_joint1
      - b_right_leg_joint1
      - f_left_leg_joint2
      - f_right_leg_joint2
      - b_left_leg_joint2
      - b_right_leg_joint2
      - f_left_leg_joint3
      - f_right_leg_joint3
      - b_left_leg_joint3
      - b_right_leg_joint3

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Hz, Defaults to 50
    action_monitor_rate: 20.0 # Hz, Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

    gains:
      left_arm_joint1:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      left_arm_joint2:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      left_arm_joint3:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0

      right_arm_joint1:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      right_arm_joint2:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      right_arm_joint3:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0

      f_right_leg_joint1:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      f_right_leg_joint2:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      f_right_leg_joint3:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0

      f_left_leg_joint1:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      f_left_leg_joint2:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      f_left_leg_joint3:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0

      b_left_leg_joint1:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      b_left_leg_joint2:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      b_left_leg_joint3:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0

      b_right_leg_joint1:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      b_right_leg_joint2:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0
      
      b_right_leg_joint3:
          p: 1500.0
          i: 10000.0
          d: 10.0
          ff_velocity_scale: 0.0


